### ISSUE TITLE
fixbar-front class covers screen when on mobile (below 550px)

### ISSUE THREAD

**Issue by garry-clawson** [theboxahaan/theboxahaan.github.io#1]
Fixbar-front class overlays screen when viewing site on mobile (or when screen is less than 550px as per media query). Tested on Chrome and Safari. Maybe try 'flex-wrap: wrap;' property to custom.css .fixbar-front class? 
<img width="517" alt="overlay" src="https://user-images.githubusercontent.com/44243266/91753757-41e50e00-ebc0-11ea-89ea-4809c5ab336b.png">

**Comment by theboxahaan** [comment]
Hey,
_Thanks for pointing it out_. No, the flex-wrap did not suffice. Instead using @media rules,  on screen size < 550px, changed the `position` property of `.fixbar-front` from `fixed ~> relative` in `custom.css`.
